import { useQuery } from "urql";
import { useRouter } from 'next/router';
import Head from "next/head";
import {  MENUS_QUERY } from "../../data/query";
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Social from '../../components/Social';
import Cursor from '../../components/Cursor';
import Posts from "../../components/Posts";
import styles from '../../styles/Page.module.css';

export default function Category(){
    
  const { query } = useRouter();

  const [results] = useQuery({
    query: MENUS_QUERY,
  });

  const {data, fetching, error} = results;

  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Error... {error.message}</p>;

  const primaryMenu = data.primaryMenus.data;
  const socials = data.socials.data;
  const footers = data.footers.data;
  
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,700;0,900;1,400&family=Inter:wght@300;400&display=swap" rel="stylesheet" />
      </Head>

      <Header
        primaryMenu={primaryMenu}
      />

      <main className={styles.main}>
        <section className={styles.col}>
          <Posts position='sx' />
          <Posts position='dx' />
        </section>
      </main>

      <Footer 
        footers={footers}
        text='Designed and developed by Daniele Benedetto'
      />

      <Social 
        socials={socials}
      />

      <Cursor />

    </div>
  );

};

