import { useQuery } from "urql";
import { useRouter } from 'next/router';
import Head from "next/head";
import { GET_CATEGORY_QUERY } from "../../data/query";
import Header from '../../components/Header';
import Footer from '../../components/Footer';
import Social from '../../components/Social';
import Cursor from '../../components/Cursor';

export default function Category(){
    
  const { query } = useRouter();

  const [results] = useQuery({
    query: GET_CATEGORY_QUERY,
    variables: {
      slug: query.slug
    }
  });

  const {data, fetching, error} = results;

  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Error... {error.message}</p>;

  const posts = data.categories.data[0].attributes.posts.data;
  const primaryMenu = data.primaryMenus.data;
  const socials = data.socials.data;
  const footers = data.footers.data;

  console.log(footers);
  
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,700;0,900;1,400&family=Inter:wght@300;400&display=swap" rel="stylesheet" />
      </Head>

      <Header
        primaryMenu={primaryMenu}
      />

      <main>
        {posts.map((item, idx) => {
          return (
            <div key={idx}>{item.attributes.title}</div>
          );
        })}
      </main>

      <Footer 
        footers={footers}
        text='Designed and developed by Daniele Benedetto'
      />

      <Social 
        socials={socials}
      />

      <Cursor />

    </div>
  );

};
