import Head from 'next/head';
import Link from 'next/link';
import Header from '../components/Header';
import Hero from '../components/Hero';
import styles from '../styles/Home.module.css';
import { primaryMenu, headerMenu, footerMenu, socialMenu } from '../data/simulate';
import Footer from '../components/Footer';
import Social from '../components/Social';

export default function Home() {

  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,700;0,900;1,400&family=Inter:wght@300;400&display=swap" rel="stylesheet" />
      </Head>

      <Header
        headerMenu={headerMenu}
      />

      <main className={styles.main}>

        <Hero
          title='👋, my name is Mattia and I am a photographer'
          textLeft='Based in Modena, Italy'
          textRight='I shoot, edit, develop and print the best moments'
          primaryMenu={primaryMenu}
        />

      </main>

      <Footer 
        footerMenu={footerMenu}
        text='Designed and developed by Daniele Benedetto'
      />

      <Social 
        socialMenu={socialMenu}
      />

    </div>
  );
}