import Head from 'next/head';

import Header from '../components/Header';
import Hero from '../components/Hero';
import Footer from '../components/Footer';
import Social from '../components/Social';
import Cursor from '../components/Cursor';

import styles from '../styles/Home.module.css';

import { HOME_QUERY } from '../data/query';

import { useQuery } from 'urql';

import { headerMenu, footerMenu, socialMenu } from '../data/simulate';

export default function Home() {

  const [results] = useQuery({
    query: HOME_QUERY
  });

  const {data, fetching, error} = results;

  if(fetching) return <p>Loading...</p>;
  if(error) return <p>Error... {error.message}</p>
    
  const home = data.home.data.attributes;
  const primaryMenu = data.primaryMenus.data;
  const categories = data.categories.data;

  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,700;0,900;1,400&family=Inter:wght@300;400&display=swap" rel="stylesheet" />
      </Head>

      <Header
        primaryMenu={primaryMenu}
      />

      <main className={styles.main}>

          <Hero
            title={home.title}
            textLeft={home.textLeft}
            textRight={home.textRight}
            image={home.image.data.attributes.url}
            categories={categories}
          />

      </main>

      <Footer 
        footerMenu={footerMenu}
        text='Designed and developed by Daniele Benedetto'
      />

      <Social 
        socialMenu={socialMenu}
      />

      <Cursor />

    </div>
  );
}
